name: SubUnZipper
run-name: ${{ github.actor }} is unzipping a Sub!
on: pull_request
jobs:
  unzip_sub:
    name: Sub Unzipper
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v3
        id: set-result
        with:
          script: |
            const branch = `${{ github.head_ref }}`
            const result = branch.split('/')[1]
            console.log(result)
            core.exportVariable('SubName', result);
            core.exportVariable('SubZipName', `${result}.zip`);
      - uses: actions/checkout@v3
      - run: composer install --ansi --no-progress --no-interaction --prefer-dist
      - uses: montudor/action-zip@v1
        with:
          args: zip -qq -r $SubZipName $SubName
