name: SubUnZipper
run-name: ${{ github.actor }} is unzipping a Sub!
on: pull_request
jobs:
  unzip_sub:
    name: Sub Unzipper
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v3
        id: set-result
        with:
          script: |
            const branch = `${{ github.head_ref }}`
            const result = branch.split('/')[1]
            console.log(result)
            core.exportVariable('SubName', result);
            core.exportVariable('SubZipName', `${result}.zip`);
      - uses: actions/checkout@v3
      - uses: montudor/action-zip@v1
        with:
          args: unzip -qq ${{ env.SubZipName }} -d ${{ env.SubName }}
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Commit files
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -a -m "Adding Sub xml"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.head_ref }}
